# Generated by Django 5.1 on 2024-08-09 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type1', models.CharField(max_length=50)),
                ('type2', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('against_grass', models.FloatField()),
                ('against_poison', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('battle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='BATTLE_INPROGRESS', max_length=50)),
                ('result', models.JSONField(blank=True, null=True)),
                ('pokemon_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_a', to='battle.pokemon')),
                ('pokemon_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_b', to='battle.pokemon')),
            ],
        ),
    ]
