# Generated by Django 5.1 on 2024-08-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_alter_pokemon_defense_alter_pokemon_hp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='against_grass',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='against_poison',
            field=models.FloatField(default=1.0),
        ),
    ]
